server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      enabled: true
      charset: UTF-8
      force: true

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

files:
  root:
    directory: ${user.home}\storage
  cron:
    delete_period: 1 0 0 * * *
